FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./
COPY tsconfig*.json ./


# Copy source code
COPY ./packages/client ./packages/client
COPY ./packages/shared ./packages/shared



# Install dependencies
RUN npm install
RUN npm run build -w @battle-snakes/shared
RUN npm run build -w @battle-snakes/client

RUN npm install -g serve
EXPOSE 3000
CMD ["serve", "-s", "./packages/client/dist", "-l", "3000"]