version: '3.8'

services:
  backend:
    container_name: battle-snakes-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '3005:3001'
    restart: unless-stopped
    networks:
      - battle-snakes-network
  frontend:
    container_name: battle-snakes-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '3004:3000'
    restart: unless-stopped
    networks:
      - web 

networks:
  web:
    external: true 
